name: Natsuki Mobile Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Extrair Natsuki
        run: |
          unzip -o Natsuki_Mobile_Build_BOSS_SECRETO_REALMENTE_CORRIGIDO.zip -d natsuki

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v4

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Compilar APK
        working-directory: natsuki/NatsukiChat
        run: gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Natsuki-APK
          path: natsuki/NatsukiChat/app/build/outputs/apk/debug/*.apk
